version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - './mariadb/data:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      - PMA_HOSTS=mariadb

  php:
    image: myphp:1.0
    container_name: php
    restart: unless-stopped
    volumes:
      - './php/php.ini:/usr/local/etc/php/php.ini'
      - './nginx/www:/var/www/html'

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - './nginx/www:/var/www/html'

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - './redis:/data'

  h5ai:
    image: awesometic/h5ai:latest
    container_name: h5ai
    restart: unless-stopped
    volumes:
      - './h5ai/config:/config'
      - './h5ai/data:/h5ai'
    environment:
      - HTPASSWD=true
      - HTPASSWD_USER=hidden

networks:
  default:
    external:
      name: nginx-proxy-manage
